let t = document.body.firstElementChild.firstElementChild 
console.log(t)
console.log(t.rows)                                              //To get all table rows
console.log(t.caption)                                           //To get table caption
console.log(t.tHead)
console.log(t.tHead.firstElementChild)
console.log(t.tFoot)
console.log(t.tBodies)                                           //Collection of <tbody> Elements
// console.log(t.rows[0].rowIndex)
console.log(t.rows[1].rowIndex)
// console.log(t.rows[2].rowIndex)
// console.log(t.rows[3].rowIndex)


// document.body.firstElementChild.firstElementChild is pointing at <table> tag







//  IN CONSOLE WRITE
// typeof document
// OUTPUT->object
// typeof window
// OUTPUT->object
 