console.log(first.className="text-black red")
console.log(first.classList)

first.classList.remove("red")
console.log(first.classList)

first.classList.add("blue")
console.log(first.classList)

first.classList.toggle("blue")
console.log(first.classList)
//TOGGLE
//If a class already present then toggle will remove it and If a class is absent it will add it  

//IN CONSOLE WRITE :-
// first.classList.toggle("blue")
// first.classList.toggle("blue")
//THEN
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")
// first.classList.toggle("red")