let nullVar=null;
let numVar=29;
let boolVar=true;
let bigIntVar=BigInt("567");
let strVar="harry";
let symbolVar=Symbol("I'm a nice Symbol");
// let undefined=undefined;
console.log(nullVar)
console.log(numVar)
console.log(boolVar)
console.log(bigIntVar)
console.log(strVar)
console.log(symbolVar)
// console.log(undefined)

console.log("DONE MY WORLD!!!")
console.log(typeof numVar)
console.log(typeof strVar)