class Animal{
    constructor(name,color){
        this.name=name
        this.color=color
    }
    run(){
        console.log(this.name="is running")
    }
    shout(){
        console.log(this.name="is shouting")
    }
    run(){
        console.log(this.name="is running")
    }
}

// THIS WE SHOULD NOT DO 
// WE WILL DO THIS IF WE ARE NOT A GOOD CODER
// class Monkey{
//     constructor(name,color){
//         this.name=name
//         this.color=color
//     }
//     run(){
//         console.log(this.name="is running")
//     }
//     shout(){
//         console.log(this.name="is shouting")
//     }
//     run(){
//         console.log(this.name="is running")
//     }
// }
