const num= new Array(1,2,3,4,5,6,7,8,9);

//Push
num.push(10)

//console.log(num.push(10)) By This are able to se length after pushing (By default Length is shown)

//Unshift
num.unshift(0)

//console.log(num.unshift(0)) By This are able to se length after unshift (By default Length is shown)

//POP
num.pop()
//console.log(num.pop()) By This are able to se length after pop (By default Length is shown)

//Shift
num.shift()
// console.log(num.shift())  By This are able to se length after shift (By default value is shown that is removed)

// num[0]=10 //Added 10 at o index

// num[0]='Yash' //Replaced 10

num[0]={num:80}

console.log()
//IN CONSOLE WRITE 
// num

//Else write in code:-
// console.log(num)