const names=['Daman','Harsh','Vansh','Daman','Harsh','Gaurav']
console.log(names)

// names.indexOf('Daman')
// names.indexOf('Vansh')

console.log(names.indexOf('Harsh'))
// console.log(names.indexOf('Vansh'))
// console.log(names.indexOf('Va'))     // Does not exist so -1

// console.log(names.indexOf('Daman',2))  // 2 means start checking from index 2


// names.lastIndexOf("Harsh")

console.log(names.lastIndexOf("Harsh"))