let names1=['Daman','Suhani','Ankush','Daman','Suhani','Gaurav']
let names2=['Agam','Aryan','Bilakshan','Akshit','Vansh','Harsh']

// Another Way To Conactenate 2 arrays
let names3=[...names1,...names2]
console.log(names3)

// Another Way To Conactenate 2 arrays
let names4=[...['Daman','Suhani','Ankush','Daman','Suhani','Gaurav'],...['Agam','Aryan','Bilakshan','Akshit','Vansh','Harsh']]
console.log(names4)