const path = require("path");
const express = require("express");
const mongoose = require("mongoose");
const cookieParser = require("cookie-parser");

const Blog = require('./models/27_blogs');

const userRoute = require('./routes/38_user');
const blogRoute = require('./routes/28_blog');
const { checkForAuthenticationCookie } = require("./27_middleware/authentication");

const app = express();
const PORT = 8000;

mongoose
    .connect('mongodb://localhost:27017/blogify')
    .then((e) => console.log('MongoDB connected'))  // 27017 is generated by writing command mongosh in terminal and blogify is the name of the database 

app.set("view engine", "ejs");                  // middleware
app.set("views", path.resolve("./views"));

app.use(express.urlencoded({extended: false}));
app.use(cookieParser());
app.use(checkForAuthenticationCookie("token"));      // Basically we are initializing cookie parser and we are checking Token // AT routes/27_index.js //  return res.cookie("token",token).redirect("/");   // if user entered correct password then we made a cookie for user named token and we redirected it to home page
app.use(express.static(path.resolve("./public")));   // means to serve everything in public folder statically


/*
app.get('/', (req,res) =>{                      // (passing user object when we render the home page)
    res.render("home",{
        user: req.user,
    });
});
*/
app.get('/', async(req,res) =>{                      // (passing user object when we render the home page)
    // const allBlogs = await Blog.find({}).sort('createdAt', -1);  // Sort w.r.t createdAt and -1 means in descending order
    const allBlogs = await Blog.find({});  //Removed sort as it gave error
    res.render("home",{
        user: req.user,
        blogs: allBlogs,
    });
});
app.use('/user', userRoute);
app.use('/blog', blogRoute);

app.listen(PORT, () => console.log(`Server Started at PORT: ${PORT}`));