const path = require("path");
const express = require("express");
const mongoose = require("mongoose");

const userRoute = require('./routes/user');

const app = express();
const PORT = 8000;

mongoose.connect('mongodb://localhost:27017/blogify').then(e => console.log('MongoDB connected'))  // 27017 is generated by writing command mongosh in terminal and blogify is the name of the database 

app.set("view engine", "ejs");                  // middleware
app.set("views", path.resolve("./views"));

app.use(express.urlencoded({extended: false}));

app.get('/', (req,res) =>{
    res.render("home");
})

app.use('/user', userRoute);

app.listen(PORT, () => console.log(`Server Started at PORT: ${PORT}`));